version: 0.0
os: linux
files:
  - source: index.js
    destination: /home/ec2-user/
hooks:
  AfterInstall:
    - location: hooks/install_dependencies
      timeout: 300
      runas: root
    - location: hooks/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: hooks/stop_server
      timeout: 300
      runas: root